run:
  concurrency: 4
  issues-exit-code: 1
  tests: true # Include test files in analysis, but we exclude them via exclude-dirs

linters:
  disable-all: true
  enable:
    - depguard
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
    - staticcheck # Explicitly enable as SA1019 implies it was used

linters-settings:
  misspell:
    locale: US
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced with standard lib errors or fmt.Errorf

issues:
  exclude-dirs:
    - third_party
    - builtin
    - examples
    - apis
    - pkg/client
    - vendor
    - test # Exclude test directory
    - testbin
  exclude-rules:
    - path: '(.+)\.go$'
      text: "SA1019: package github.com/golang/protobuf/proto is deprecated"
    # Exclude Go 1.23 specific deprecations to pass CI with newer linter
    - text: "SA1019"
      linters:
        - staticcheck
