/*
Copyright 2025 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	http "net/http"

	appsv1beta1 "github.com/openkruise/kruise/apis/apps/v1beta1"
	scheme "github.com/openkruise/kruise/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type AppsV1beta1Interface interface {
	RESTClient() rest.Interface
	AdvancedCronJobsGetter
	BroadcastJobsGetter
	CloneSetsGetter
	DaemonSetsGetter
	ImageListPullJobsGetter
	ImagePullJobsGetter
	NodeImagesGetter
	SidecarSetsGetter
	StatefulSetsGetter
}

// AppsV1beta1Client is used to interact with features provided by the apps.kruise.io group.
type AppsV1beta1Client struct {
	restClient rest.Interface
}

func (c *AppsV1beta1Client) AdvancedCronJobs(namespace string) AdvancedCronJobInterface {
	return newAdvancedCronJobs(c, namespace)
}

func (c *AppsV1beta1Client) BroadcastJobs(namespace string) BroadcastJobInterface {
	return newBroadcastJobs(c, namespace)
}

func (c *AppsV1beta1Client) CloneSets(namespace string) CloneSetInterface {
	return newCloneSets(c, namespace)
}

func (c *AppsV1beta1Client) DaemonSets(namespace string) DaemonSetInterface {
	return newDaemonSets(c, namespace)
}

func (c *AppsV1beta1Client) ImageListPullJobs(namespace string) ImageListPullJobInterface {
	return newImageListPullJobs(c, namespace)
}

func (c *AppsV1beta1Client) ImagePullJobs(namespace string) ImagePullJobInterface {
	return newImagePullJobs(c, namespace)
}

func (c *AppsV1beta1Client) NodeImages() NodeImageInterface {
	return newNodeImages(c)
}

func (c *AppsV1beta1Client) SidecarSets() SidecarSetInterface {
	return newSidecarSets(c)
}

func (c *AppsV1beta1Client) StatefulSets(namespace string) StatefulSetInterface {
	return newStatefulSets(c, namespace)
}

// NewForConfig creates a new AppsV1beta1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*AppsV1beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new AppsV1beta1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*AppsV1beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &AppsV1beta1Client{client}, nil
}

// NewForConfigOrDie creates a new AppsV1beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *AppsV1beta1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new AppsV1beta1Client for the given RESTClient.
func New(c rest.Interface) *AppsV1beta1Client {
	return &AppsV1beta1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := appsv1beta1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *AppsV1beta1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
