# permissions for end users to edit ephemeraljobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ephemeraljob-editor-role
rules:
- apiGroups:
  - apps.kruise.io
  resources:
  - ephemeraljobs
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kruise.io
  resources:
  - ephemeraljobs/status
  verbs:
  - get
