# permissions for end users to edit podmarkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podmarker-editor-role
rules:
- apiGroups:
  - apps.kruise.io
  resources:
  - podmarkers
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kruise.io
  resources:
  - podmarkers/status
  verbs:
  - get
