# permissions for end users to view resourcedistributions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcedistribution-viewer-role
rules:
- apiGroups:
  - apps.kruise.io
  resources:
  - resourcedistributions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.kruise.io
  resources:
  - resourcedistributions/status
  verbs:
  - get
