# permissions for end users to edit workloadspreads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workloadspread-editor-role
rules:
- apiGroups:
  - apps.kruise.io
  resources:
  - workloadspreads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kruise.io
  resources:
  - workloadspreads/status
  verbs:
  - get
