# permissions for end users to view workloadspreads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workloadspread-viewer-role
rules:
- apiGroups:
  - apps.kruise.io
  resources:
  - workloadspreads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.kruise.io
  resources:
  - workloadspreads/status
  verbs:
  - get
