apiVersion: apps.kruise.io/v1alpha1
kind: ResourceDistribution
metadata:
  name: sample
spec:
  resource:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: game-demo
    data:
      player_initial_lives: "3"
      ui_properties_file_name: "user-interface.properties"
      game.properties: |
        enemy.types=aliens,monsters
        player.maximum-lives=5
      user-interface.properties: |
        color.good=purple
        color.bad=yellow
        allow.textmode=true
  targets:
    excludedNamespaces:
      - name: ns-3
    includedNamespaces:
      - name: ns-1
      - name: ns-2
      - name: ns-3
      - name: ns-4