/*
Copyright 2021 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AdvancedCronJobListerExpansion allows custom methods to be added to
// AdvancedCronJobLister.
type AdvancedCronJobListerExpansion interface{}

// AdvancedCronJobNamespaceListerExpansion allows custom methods to be added to
// AdvancedCronJobNamespaceLister.
type AdvancedCronJobNamespaceListerExpansion interface{}

// BroadcastJobListerExpansion allows custom methods to be added to
// BroadcastJobLister.
type BroadcastJobListerExpansion interface{}

// BroadcastJobNamespaceListerExpansion allows custom methods to be added to
// BroadcastJobNamespaceLister.
type BroadcastJobNamespaceListerExpansion interface{}

// CloneSetListerExpansion allows custom methods to be added to
// CloneSetLister.
type CloneSetListerExpansion interface{}

// CloneSetNamespaceListerExpansion allows custom methods to be added to
// CloneSetNamespaceLister.
type CloneSetNamespaceListerExpansion interface{}

// ContainerRecreateRequestListerExpansion allows custom methods to be added to
// ContainerRecreateRequestLister.
type ContainerRecreateRequestListerExpansion interface{}

// ContainerRecreateRequestNamespaceListerExpansion allows custom methods to be added to
// ContainerRecreateRequestNamespaceLister.
type ContainerRecreateRequestNamespaceListerExpansion interface{}

// DaemonSetListerExpansion allows custom methods to be added to
// DaemonSetLister.
type DaemonSetListerExpansion interface{}

// DaemonSetNamespaceListerExpansion allows custom methods to be added to
// DaemonSetNamespaceLister.
type DaemonSetNamespaceListerExpansion interface{}

// EphemeralJobListerExpansion allows custom methods to be added to
// EphemeralJobLister.
type EphemeralJobListerExpansion interface{}

// EphemeralJobNamespaceListerExpansion allows custom methods to be added to
// EphemeralJobNamespaceLister.
type EphemeralJobNamespaceListerExpansion interface{}

// ImagePullJobListerExpansion allows custom methods to be added to
// ImagePullJobLister.
type ImagePullJobListerExpansion interface{}

// ImagePullJobNamespaceListerExpansion allows custom methods to be added to
// ImagePullJobNamespaceLister.
type ImagePullJobNamespaceListerExpansion interface{}

// NodeImageListerExpansion allows custom methods to be added to
// NodeImageLister.
type NodeImageListerExpansion interface{}

// PodMarkerListerExpansion allows custom methods to be added to
// PodMarkerLister.
type PodMarkerListerExpansion interface{}

// PodMarkerNamespaceListerExpansion allows custom methods to be added to
// PodMarkerNamespaceLister.
type PodMarkerNamespaceListerExpansion interface{}

// ResourceDistributionListerExpansion allows custom methods to be added to
// ResourceDistributionLister.
type ResourceDistributionListerExpansion interface{}

// SidecarSetListerExpansion allows custom methods to be added to
// SidecarSetLister.
type SidecarSetListerExpansion interface{}

// StatefulSetListerExpansion allows custom methods to be added to
// StatefulSetLister.
type StatefulSetListerExpansion interface{}

// StatefulSetNamespaceListerExpansion allows custom methods to be added to
// StatefulSetNamespaceLister.
type StatefulSetNamespaceListerExpansion interface{}

// UnitedDeploymentListerExpansion allows custom methods to be added to
// UnitedDeploymentLister.
type UnitedDeploymentListerExpansion interface{}

// UnitedDeploymentNamespaceListerExpansion allows custom methods to be added to
// UnitedDeploymentNamespaceLister.
type UnitedDeploymentNamespaceListerExpansion interface{}

// WorkloadSpreadListerExpansion allows custom methods to be added to
// WorkloadSpreadLister.
type WorkloadSpreadListerExpansion interface{}

// WorkloadSpreadNamespaceListerExpansion allows custom methods to be added to
// WorkloadSpreadNamespaceLister.
type WorkloadSpreadNamespaceListerExpansion interface{}
