/*
Copyright 2025 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	appsv1alpha1 "github.com/openkruise/kruise/apis/apps/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// WorkloadSpreadLister helps list WorkloadSpreads.
// All objects returned here must be treated as read-only.
type WorkloadSpreadLister interface {
	// List lists all WorkloadSpreads in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1alpha1.WorkloadSpread, err error)
	// WorkloadSpreads returns an object that can list and get WorkloadSpreads.
	WorkloadSpreads(namespace string) WorkloadSpreadNamespaceLister
	WorkloadSpreadListerExpansion
}

// workloadSpreadLister implements the WorkloadSpreadLister interface.
type workloadSpreadLister struct {
	listers.ResourceIndexer[*appsv1alpha1.WorkloadSpread]
}

// NewWorkloadSpreadLister returns a new WorkloadSpreadLister.
func NewWorkloadSpreadLister(indexer cache.Indexer) WorkloadSpreadLister {
	return &workloadSpreadLister{listers.New[*appsv1alpha1.WorkloadSpread](indexer, appsv1alpha1.Resource("workloadspread"))}
}

// WorkloadSpreads returns an object that can list and get WorkloadSpreads.
func (s *workloadSpreadLister) WorkloadSpreads(namespace string) WorkloadSpreadNamespaceLister {
	return workloadSpreadNamespaceLister{listers.NewNamespaced[*appsv1alpha1.WorkloadSpread](s.ResourceIndexer, namespace)}
}

// WorkloadSpreadNamespaceLister helps list and get WorkloadSpreads.
// All objects returned here must be treated as read-only.
type WorkloadSpreadNamespaceLister interface {
	// List lists all WorkloadSpreads in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1alpha1.WorkloadSpread, err error)
	// Get retrieves the WorkloadSpread from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*appsv1alpha1.WorkloadSpread, error)
	WorkloadSpreadNamespaceListerExpansion
}

// workloadSpreadNamespaceLister implements the WorkloadSpreadNamespaceLister
// interface.
type workloadSpreadNamespaceLister struct {
	listers.ResourceIndexer[*appsv1alpha1.WorkloadSpread]
}
